apiVersion: v1
kind: ReplicationController
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: hqmq/blog:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 25m
            memory: 10M
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: blog
