apiVersion: v1
kind: ReplicationController
metadata:
  name: home
  labels:
    app: home
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: hqmq/home:0.4.2
        imagePullPolicy: Always
        command: ["elixir"]
        args: ["--no-halt", "--cookie", "$(COOKIE)", "--name", "home@$(POD_IP)", "-S", "mix", "phx.server"]
        env:
        - name: COOKIE
          valueFrom:
            secretKeyRef:
              name: home
              key: cookie
        - name: ONE_SIGNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: home
              key: one_signal_api_key
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: home
              key: secret_key_base
        ports:
          - containerPort: 4000
        resources:
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
spec:
  type: NodePort
  ports:
  - port: 4000
  selector:
    app: home
