apiVersion: v1
kind: ReplicationController
metadata:
  name: load-balancer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      volumes:
      - name: "config"
        configMap:
          name: "load-balancer-config"
      - name: load-balancer-secrets
        secret:
          secretName: load-balancer
      containers:
      - image: nginx:1.15-alpine
        imagePullPolicy: Always
        name: load-balancer
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: 25m
            memory: 10M
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "load_balancer_nginx.conf"
        - name: load-balancer-secrets
          mountPath: "/etc/ssl/nginx"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: load-balancer
