apiVersion: v1
kind: ReplicationController
metadata:
  name: ref
  labels:
    app: ref
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ref
    spec:
      containers:
      - name: ref
        image: hqmq/ref:0.1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: ref
  labels:
    app: ref
spec:
  type: NodePort
  ports:
  - port: 4000
  selector:
    app: ref
